#ifdef OPLUS_FEATURE_HEALTHINFO
#Jiheng.Xie@TECH.BSP.Performance.Sched, 2020/04/07, Add for Healthinfo monitor
obj-$(CONFIG_OPLUS_HEALTHINFO)  +=  cpuload.o
#Liujie.Xie@TECH.BSP.Kernel.Sched, 2020/05/07, Add for Jank monitor
obj-$(CONFIG_OPLUS_JANK_INFO)  +=  jank_monitor.o
#endif /* OPLUS_FEATURE_HEALTHINFO */
obj-$(CONFIG_FG_TASK_UID)  +=  fg_uid/
