# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

#ifdef OPLUS_FEATURE_ESIM
#ChenGuoyao@NETWORK.SIM,2020/06/10, Add for eSIM
obj-$(CONFIG_OPLUS_GPIO)    +=  oplus_gpio/
#endif /* OPLUS_FEATURE_ESIM */
